name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - run: npm ci

      - name: Build Firefox
        run: npm run build:firefox
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: firefox
          path: dist.zip

      - name: Build Chrome
        run: npm run build:chrome
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: chrome
          path: dist.zip
