name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: npm

      - name: Build Firefox
        run: make build-firefox
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox
          path: artifacts/firefox.zip

      - name: Build Chrome
        run: make build-chrome
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome
          path: artifacts/chrome.zip

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
          cache: npm

      - name: Install dependencies
        run: make ci

      - name: Typecheck TypeScript
        run: make compile
